from app.database import SessionLocal
from app.models.question_bank import QuestionBank

questions = [
    # =============================================
    # Unit 1: Present Time (15 Questions - Grammar)
    # =============================================
    {"question": "He ____ constantly complaining about the temperature in the office, which is getting on my nerves.",
     "options": ["is", "has been", "does", "was"], "correct": "is", "difficulty": "C1", "topic": "present time"},
    {"question": "I ____ to understand what the lecturer is getting at, but her argument is extremely convoluted.",
     "options": ["try", "am trying", "have tried", "tries"], "correct": "am trying", "difficulty": "C1", "topic": "present time"},
    {"question": "By the time you finish reading this, I ____ for the airport.",
     "options": ["will have left", "will be leaving", "leave", "am leaving"], "correct": "am leaving", "difficulty": "B2", "topic": "present time"},
    {"question": "The board of directors ____ a meeting tomorrow at noon to discuss the merger.",
     "options": ["is having", "have", "are to have", "has"], "correct": "is having", "difficulty": "C1", "topic": "present time"},
    {"question": "You look absolutely exhausted! What ____ all morning?",
     "options": ["have you done", "did you do", "have you been doing", "do you do"], "correct": "have you been doing", "difficulty": "B2", "topic": "present time"},
    {"question": "I ____ this software for years, but I still discover new features occasionally.",
     "options": ["am using", "use", "have been using", "have used"], "correct": "have been using", "difficulty": "C1", "topic": "present time"},
    {"question": "The package ____ to contain highly sensitive documents.",
     "options": ["appears", "is appearing", "has appeared", "appear"], "correct": "appears", "difficulty": "C1", "topic": "present time"},
    {"question": "Whenever I visit my grandmother, she ____ me stories about her youth.",
     "options": ["is telling", "tells", "has told", "telling"], "correct": "tells", "difficulty": "B1", "topic": "present time"},
    {"question": "To be honest, I ____ that your proposal is the most viable option we have.",
     "options": ["am thinking", "have thought", "think", "was thinking"], "correct": "think", "difficulty": "C1", "topic": "present time"},
    {"question": "Don't bother calling her now; she ____ an interview and won't answer.",
     "options": ["has", "is having", "has had", "will have"], "correct": "is having", "difficulty": "B2", "topic": "present time"},
    {"question": "She ____ her keys! This is the third time this week.",
     "options": ["has lost", "is losing", "loses", "has been losing"], "correct": "has lost", "difficulty": "B2", "topic": "present time"},
    {"question": "Water ____ at 100 degrees Celsius under standard atmospheric pressure.",
     "options": ["is boiling", "boil", "has boiled", "boils"], "correct": "boils", "difficulty": "A2", "topic": "present time"},
    {"question": "My car broke down, so I ____ my brother's vehicle until mine is repaired.",
     "options": ["use", "have used", "am using", "will use"], "correct": "am using", "difficulty": "B2", "topic": "present time"},
    {"question": "In the final act of the play, the protagonist ____ the truth about his lineage.",
     "options": ["is discovering", "discover", "discovers", "has discovered"], "correct": "discovers", "difficulty": "C1", "topic": "present time"},
    {"question": "It ____ that the company will announce significant layoffs next quarter.",
     "options": ["is believed", "believes", "is believing", "has believed"], "correct": "is believed", "difficulty": "C2", "topic": "present time"},

    # =============================================
    # Unit 2: Thinking and Learning (15 Questions - Vocabulary)
    # =============================================
    {"question": "It takes a while to ____ all the information in a long lecture.",
     "options": ["take in", "take up", "take off", "take over"], "correct": "take in", "difficulty": "B2", "topic": "thinking and learning"},
    {"question": "She has a remarkable ability to ____ new facts quickly.",
     "options": ["retain", "remain", "refrain", "regain"], "correct": "retain", "difficulty": "C1", "topic": "thinking and learning"},
    {"question": "We need to ____ how to solve this problem before the deadline.",
     "options": ["figure out", "find out", "give up", "make up"], "correct": "figure out", "difficulty": "B1", "topic": "thinking and learning"},
    {"question": "He ____ Spanish very quickly while living in Madrid.",
     "options": ["picked up", "picked off", "picked out", "picked over"], "correct": "picked up", "difficulty": "B2", "topic": "thinking and learning"},
    {"question": "If you want to pass, you'll have to learn this poem ____.",
     "options": ["by heart", "by hand", "by mind", "by head"], "correct": "by heart", "difficulty": "A2", "topic": "thinking and learning"},
    {"question": "Success in this field requires a high level of ____ skill.",
     "options": ["cognitive", "content", "condition", "context"], "correct": "cognitive", "difficulty": "C1", "topic": "thinking and learning"},
    {"question": "She is making excellent ____ in her piano lessons.",
     "options": ["progress", "process", "program", "project"], "correct": "progress", "difficulty": "B1", "topic": "thinking and learning"},
    {"question": "He decided to ____ into the effects of climate change.",
     "options": ["do research", "make research", "have research", "get research"], "correct": "do research", "difficulty": "B2", "topic": "thinking and learning"},
    {"question": "After years of practice, he finally ____ enough experience to lead the team.",
     "options": ["gained", "won", "earned", "made"], "correct": "gained", "difficulty": "C1", "topic": "thinking and learning"},
    {"question": "She is such a ____ learner; she understands everything the first time.",
     "options": ["quick", "fast", "swift", "rapid"], "correct": "quick", "difficulty": "A2", "topic": "thinking and learning"},
    {"question": "The main ____ of the experiment was to test the hypothesis.",
     "options": ["objective", "objection", "observer", "obstacle"], "correct": "objective", "difficulty": "B2", "topic": "thinking and learning"},
    {"question": "Studying abroad can help you ____ a new perspective on life.",
     "options": ["acquire", "require", "inquire", "inspire"], "correct": "acquire", "difficulty": "C1", "topic": "thinking and learning"},
    {"question": "He is a fast ____ and always gets the highest marks.",
     "options": ["learner", "learning", "learned", "learns"], "correct": "learner", "difficulty": "A2", "topic": "thinking and learning"},
    {"question": "The ____ process can be difficult but rewarding.",
     "options": ["learning", "learner", "learned", "learns"], "correct": "learning", "difficulty": "A1", "topic": "thinking and learning"},
    {"question": "I can't ____ the name of that actor right now.",
     "options": ["recall", "remind", "record", "repeat"], "correct": "recall", "difficulty": "B2", "topic": "thinking and learning"},

    # =============================================
    # Unit 3: Past Time (15 Questions - Grammar)
    # =============================================
    {"question": "By the time the paramedics arrived, the building ____ completely.",
     "options": ["collapsed", "had collapsed", "has collapsed", "was collapsing"], "correct": "had collapsed", "difficulty": "C1", "topic": "past time"},
    {"question": "I ____ about calling you all day yesterday, but I never got around to it.",
     "options": ["thought", "was thinking", "had thought", "had been thinking"], "correct": "was thinking", "difficulty": "B2", "topic": "past time"},
    {"question": "As a child, I ____ spend hours playing in the woods behind our house.",
     "options": ["used to", "would", "both are correct", "none are correct"], "correct": "both are correct", "difficulty": "C1", "topic": "past time"},
    {"question": "She ____ at the company for over twenty years before she finally decided to retire.",
     "options": ["worked", "was working", "had worked", "had been working"], "correct": "had been working", "difficulty": "C1", "topic": "past time"},
    {"question": "He was breathless because he ____ all the way from the station.",
     "options": ["ran", "was running", "had run", "had been running"], "correct": "had been running", "difficulty": "B2", "topic": "past time"},
    {"question": "Little ____ we know that our lives were about to change forever.",
     "options": ["did", "had", "would", "do"], "correct": "did", "difficulty": "C2", "topic": "past time"},
    {"question": "Hardly ____ the meeting started when the fire alarm went off.",
     "options": ["did", "has", "had", "was"], "correct": "had", "difficulty": "C1", "topic": "past time"},
    {"question": "I ____ my keys four times already this month; I really must be more careful.",
     "options": ["lost", "was losing", "had lost", "have lost"], "correct": "have lost", "difficulty": "B1", "topic": "past time"},
    {"question": "When I was younger, I ____ like spinach, but now I love it.",
     "options": ["didn't used to", "didn't use to", "wouldn't", "hadn't"], "correct": "didn't use to", "difficulty": "B2", "topic": "past time"},
    {"question": "The detective noticed that someone ____ the lock on the safe.",
     "options": ["tampered", "was tampering", "had tampered", "had been tampering"], "correct": "had tampered", "difficulty": "C1", "topic": "past time"},
    {"question": "It was the first time she ____ such an impressive performance.",
     "options": ["saw", "was seeing", "had seen", "has seen"], "correct": "had seen", "difficulty": "C1", "topic": "past time"},
    {"question": "They ____ for three hours when it finally started to rain.",
     "options": ["drove", "were driving", "had driven", "had been driving"], "correct": "had been driving", "difficulty": "B2", "topic": "past time"},
    {"question": "I ____ to the cinema last night with some old friends from university.",
     "options": ["go", "went", "had gone", "was going"], "correct": "went", "difficulty": "A2", "topic": "past time"},
    {"question": "No sooner ____ the plane touched down than the passengers began to unbuckle their seatbelts.",
     "options": ["did", "has", "had", "was"], "correct": "had", "difficulty": "C2", "topic": "past time"},
    {"question": "At that time, the company ____ through a period of rapid expansion.",
     "options": ["went", "was going", "had gone", "had been going"], "correct": "was going", "difficulty": "B2", "topic": "past time"},

    # =============================================
    # Unit 4: Change and Technology (15 Questions - Vocabulary)
    # =============================================
    {"question": "The company had to ____ its strategy to survive the economic downturn.",
     "options": ["adapt", "adopt", "adept", "admit"], "correct": "adapt", "difficulty": "C1", "topic": "change and technology"},
    {"question": "It's important to ____ your files regularly to prevent data loss.",
     "options": ["back up", "back out", "back down", "back away"], "correct": "back up", "difficulty": "B2", "topic": "change and technology"},
    {"question": "The new software will ____ the way we handle customer data.",
     "options": ["revolutionize", "reveal", "revolve", "reverse"], "correct": "revolutionize", "difficulty": "C1", "topic": "change and technology"},
    {"question": "Deciding to quit his job without another one lined up was a ____ in the dark.",
     "options": ["leap", "jump", "hop", "skip"], "correct": "leap", "difficulty": "C1", "topic": "change and technology"},
    {"question": "He had a ____ of heart and decided to stay with the company.",
     "options": ["change", "turn", "shift", "move"], "correct": "change", "difficulty": "B2", "topic": "change and technology"},
    {"question": "Please ____ your password to access the system.",
     "options": ["key in", "key out", "key up", "key down"], "correct": "key in", "difficulty": "B1", "topic": "change and technology"},
    {"question": "Over time, the old traditions began to ____ away.",
     "options": ["fade", "fall", "fly", "flow"], "correct": "fade", "difficulty": "B2", "topic": "change and technology"},
    {"question": "The scientist needed to ____ the experimental data before publishing.",
     "options": ["refine", "define", "confine", "design"], "correct": "refine", "difficulty": "C1", "topic": "change and technology"},
    {"question": "We had to ____ the layout of the office to make room for the new team.",
     "options": ["change around", "change off", "change out", "change up"], "correct": "change around", "difficulty": "B2", "topic": "change and technology"},
    {"question": "They decided to ____ with tradition and have a small wedding.",
     "options": ["break", "snap", "crack", "split"], "correct": "break", "difficulty": "B2", "topic": "change and technology"},
    {"question": "The machine started to ____ out after years of constant use.",
     "options": ["wear", "tear", "bear", "fear"], "correct": "wear", "difficulty": "B1", "topic": "change and technology"},
    {"question": "She needs to ____ her schedule to accommodate the new project.",
     "options": ["adjust", "admit", "adopt", "adapt"], "correct": "adjust", "difficulty": "B2", "topic": "change and technology"},
    {"question": "The small cabin was ____ into a beautiful holiday home.",
     "options": ["made", "taken", "given", "put"], "correct": "made", "difficulty": "B2", "topic": "change and technology"},
    {"question": "His life underwent a complete ____ after he moved abroad.",
     "options": ["transformation", "transportation", "translation", "transaction"], "correct": "transformation", "difficulty": "C1", "topic": "change and technology"},
    {"question": "The laws are being ____ to reflect modern society.",
     "options": ["amended", "attended", "intended", "extended"], "correct": "amended", "difficulty": "C1", "topic": "change and technology"},

    # =============================================
    # Unit 5: Future Time (15 Questions - Grammar)
    # =============================================
    {"question": "This time tomorrow, I ____ across the Atlantic.",
     "options": ["will be flying", "will fly", "am flying", "will have flown"], "correct": "will be flying", "difficulty": "B2", "topic": "future time"},
    {"question": "By 2025, they ____ the new bridge.",
     "options": ["will have finished", "will finish", "will be finishing", "have finished"], "correct": "will have finished", "difficulty": "B2", "topic": "future time"},
    {"question": "When you arrive, I ____ here for exactly ten years.",
     "options": ["will have been living", "will live", "am living", "will be living"], "correct": "will have been living", "difficulty": "C1", "topic": "future time"},
    {"question": "The train ____ to arrive at 10:30, according to the schedule.",
     "options": ["is due", "is about", "is point", "is on"], "correct": "is due", "difficulty": "B2", "topic": "future time"},
    {"question": "I ____ to leave when the phone rang.",
     "options": ["was about", "was due", "was point", "was on"], "correct": "was about", "difficulty": "B2", "topic": "future time"},
    {"question": "Hurry up! The ceremony is on the ____ of starting.",
     "options": ["point", "edge", "verge", "border"], "correct": "point", "difficulty": "C1", "topic": "future time"},
    {"question": "Next month, I ____ for this company for five years.",
     "options": ["will have been working", "will work", "am working", "will be working"], "correct": "will have been working", "difficulty": "C1", "topic": "future time"},
    {"question": "Don't call me at 8:00, as I ____ dinner then.",
     "options": ["will be having", "will have", "am having", "will have had"], "correct": "will be having", "difficulty": "B2", "topic": "future time"},
    {"question": "By the end of the day, I ____ all these reports.",
     "options": ["will have read", "will read", "am reading", "will be reading"], "correct": "will have read", "difficulty": "B2", "topic": "future time"},
    {"question": "I'm sure that machines ____ all the work in the future.",
     "options": ["will do", "are doing", "do", "will be doing"], "correct": "will do", "difficulty": "A2", "topic": "future time"},
    {"question": "Look at those clouds! It ____ rain.",
     "options": ["is going to", "will", "shall", "is being"], "correct": "is going to", "difficulty": "A2", "topic": "future time"},
    {"question": "I ____ you as soon as I get home.",
     "options": ["will call", "call", "am calling", "am going to call"], "correct": "will call", "difficulty": "A2", "topic": "future time"},
    {"question": "This time next week, we ____ on a beach in Hawaii.",
     "options": ["will be lying", "will lie", "are lying", "will have lain"], "correct": "will be lying", "difficulty": "B2", "topic": "future time"},
    {"question": "By the time he retires, he ____ for forty years.",
     "options": ["will have been working", "will work", "will be working", "works"], "correct": "will have been working", "difficulty": "C1", "topic": "future time"},
    {"question": "The President ____ to give a speech at the opening ceremony.",
     "options": ["is to", "is about", "is going", "will"], "correct": "is to", "difficulty": "C1", "topic": "future time"},

    # =============================================
    # Unit 6: Time and Work (15 Questions - Vocabulary)
    # =============================================
    {"question": "After 30 years at the firm, he finally decided to ____.",
     "options": ["retire", "retreat", "resign", "return"], "correct": "retire", "difficulty": "B1", "topic": "time and work"},
    {"question": "She was ____ after the company downsized its workforce.",
     "options": ["made redundant", "made absent", "made vacant", "made idle"], "correct": "made redundant", "difficulty": "C1", "topic": "time and work"},
    {"question": "He had to ____ a lot of overtime to meet the project deadline.",
     "options": ["do", "make", "have", "get"], "correct": "do", "difficulty": "B2", "topic": "time and work"},
    {"question": "I need to ____ my notice by the end of the week.",
     "options": ["hand in", "hand out", "hand over", "hand off"], "correct": "hand in", "difficulty": "B2", "topic": "time and work"},
    {"question": "She really needs to ____ down and focus on her dissertation.",
     "options": ["knuckle", "buckle", "settle", "calm"], "correct": "knuckle", "difficulty": "C1", "topic": "time and work"},
    {"question": "Working against the ____ is always stressful.",
     "options": ["clock", "time", "watch", "hour"], "correct": "clock", "difficulty": "B2", "topic": "time and work"},
    {"question": "He was burning the midnight ____ to finish the report.",
     "options": ["oil", "candle", "lamp", "fire"], "correct": "oil", "difficulty": "B2", "topic": "time and work"},
    {"question": "The company decided to ____ on 50 new employees.",
     "options": ["take", "put", "set", "bring"], "correct": "take", "difficulty": "B2", "topic": "time and work"},
    {"question": "It's a ____ job with no chance of promotion whatsoever.",
     "options": ["dead-end", "blind-end", "closed-end", "no-end"], "correct": "dead-end", "difficulty": "B2", "topic": "time and work"},
    {"question": "One of the ____ of the job is a company car.",
     "options": ["perks", "parks", "peaks", "parts"], "correct": "perks", "difficulty": "C1", "topic": "time and work"},
    {"question": "Everyone in the team needs to pull their ____.",
     "options": ["weight", "load", "share", "part"], "correct": "weight", "difficulty": "B2", "topic": "time and work"},
    {"question": "She ____ up her own business after leaving university.",
     "options": ["set", "put", "made", "got"], "correct": "set", "difficulty": "B1", "topic": "time and work"},
    {"question": "He earns a good ____ working as a freelance designer.",
     "options": ["living", "life", "salary", "pay"], "correct": "living", "difficulty": "B2", "topic": "time and work"},
    {"question": "Due to budget cuts, the factory had to ____ off 200 workers.",
     "options": ["lay", "put", "set", "take"], "correct": "lay", "difficulty": "C1", "topic": "time and work"},
    {"question": "Job ____ is more important than a high salary for many workers.",
     "options": ["satisfaction", "completion", "fulfilment", "achievement"], "correct": "satisfaction", "difficulty": "B1", "topic": "time and work"},

    # =============================================
    # Unit 7: Passives & Causatives (15 Questions - Grammar)
    # =============================================
    {"question": "The new hospital ____ by the end of next year.",
     "options": ["will have been built", "will be building", "will build", "is building"], "correct": "will have been built", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "It ____ that the Prime Minister is considering resignation.",
     "options": ["is reported", "reports", "is reporting", "has reporting"], "correct": "is reported", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "She had her hair ____ at the new salon in town.",
     "options": ["cut", "cutting", "to cut", "cuts"], "correct": "cut", "difficulty": "B2", "topic": "passives and causatives"},
    {"question": "The suspect is believed ____ the country last night.",
     "options": ["to have left", "to leave", "leaving", "left"], "correct": "to have left", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "I need to get my computer ____ before the presentation.",
     "options": ["repaired", "repairing", "to repair", "repair"], "correct": "repaired", "difficulty": "B2", "topic": "passives and causatives"},
    {"question": "The children were made ____ their rooms before going out.",
     "options": ["to tidy", "tidy", "tidying", "tidied"], "correct": "to tidy", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "He is said ____ one of the richest men in the country.",
     "options": ["to be", "being", "be", "is"], "correct": "to be", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "She ____ her house broken into while she was on holiday.",
     "options": ["had", "got", "made", "let"], "correct": "had", "difficulty": "B2", "topic": "passives and causatives"},
    {"question": "The roof needs ____ before winter arrives.",
     "options": ["repairing", "to repair", "repair", "repaired"], "correct": "repairing", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "Having ____ about the danger, they decided not to climb the mountain.",
     "options": ["been warned", "warning", "been warning", "warned"], "correct": "been warned", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "The manager got the team ____ overtime to finish the project.",
     "options": ["to work", "work", "working", "worked"], "correct": "to work", "difficulty": "B2", "topic": "passives and causatives"},
    {"question": "It is widely ____ that the economy will improve next year.",
     "options": ["expected", "expecting", "expect", "expects"], "correct": "expected", "difficulty": "B2", "topic": "passives and causatives"},
    {"question": "The bridge ____ in 1894 and has been in use ever since.",
     "options": ["was constructed", "constructed", "has constructed", "is constructed"], "correct": "was constructed", "difficulty": "B1", "topic": "passives and causatives"},
    {"question": "She is thought ____ working on a new novel.",
     "options": ["to be", "being", "be", "is"], "correct": "to be", "difficulty": "C1", "topic": "passives and causatives"},
    {"question": "I'll have the electrician ____ the wiring tomorrow.",
     "options": ["check", "to check", "checking", "checked"], "correct": "check", "difficulty": "C1", "topic": "passives and causatives"},

    # =============================================
    # Unit 8: Movement & Transport (15 Questions - Vocabulary)
    # =============================================
    {"question": "We need to ____ off early if we want to avoid the traffic.",
     "options": ["set", "take", "get", "put"], "correct": "set", "difficulty": "B1", "topic": "movement and transport"},
    {"question": "The car ____ down on the motorway and we had to call for help.",
     "options": ["broke", "fell", "shut", "ran"], "correct": "broke", "difficulty": "B1", "topic": "movement and transport"},
    {"question": "Can you ____ me up at the station at 6 o'clock?",
     "options": ["pick", "take", "bring", "get"], "correct": "pick", "difficulty": "A2", "topic": "movement and transport"},
    {"question": "The police officer asked the driver to ____ over to the side of the road.",
     "options": ["pull", "push", "move", "drag"], "correct": "pull", "difficulty": "B2", "topic": "movement and transport"},
    {"question": "There is always ____ traffic during rush hour in the city centre.",
     "options": ["heavy", "strong", "hard", "thick"], "correct": "heavy", "difficulty": "B1", "topic": "movement and transport"},
    {"question": "I'll ____ you off at the airport on my way to work.",
     "options": ["drop", "take", "leave", "put"], "correct": "drop", "difficulty": "B2", "topic": "movement and transport"},
    {"question": "We managed to ____ the train with seconds to spare.",
     "options": ["catch", "take", "grab", "reach"], "correct": "catch", "difficulty": "B1", "topic": "movement and transport"},
    {"question": "Let's hit the ____ — we've got a long drive ahead.",
     "options": ["road", "way", "path", "route"], "correct": "road", "difficulty": "B2", "topic": "movement and transport"},
    {"question": "She felt she was at a ____ in her life and needed to make a big decision.",
     "options": ["crossroads", "junction", "turning", "corner"], "correct": "crossroads", "difficulty": "C1", "topic": "movement and transport"},
    {"question": "The passengers were asked to ____ the plane through the rear exit.",
     "options": ["disembark", "depart", "dismount", "discharge"], "correct": "disembark", "difficulty": "C1", "topic": "movement and transport"},
    {"question": "It was a ____ flight from London to Sydney with a brief stopover in Singapore.",
     "options": ["long-haul", "long-run", "long-term", "long-range"], "correct": "long-haul", "difficulty": "B2", "topic": "movement and transport"},
    {"question": "Could you give me a ____ to the station? My car is in the garage.",
     "options": ["lift", "drive", "ride", "push"], "correct": "lift", "difficulty": "B1", "topic": "movement and transport"},
    {"question": "The city suffers from severe ____ during peak hours.",
     "options": ["congestion", "confusion", "connection", "construction"], "correct": "congestion", "difficulty": "B2", "topic": "movement and transport"},
    {"question": "The ____ was so high that we decided to drive instead of taking the train.",
     "options": ["fare", "fee", "fine", "rate"], "correct": "fare", "difficulty": "B2", "topic": "movement and transport"},
    {"question": "He was caught driving well above the speed ____ on the motorway.",
     "options": ["limit", "line", "level", "law"], "correct": "limit", "difficulty": "B1", "topic": "movement and transport"},

    # =============================================
    # Unit 9: Modals & Semi-modals (15 Questions - Grammar)
    # =============================================
    {"question": "You ____ have told me earlier! I could have helped.",
     "options": ["should", "must", "would", "might"], "correct": "should", "difficulty": "B2", "topic": "modals"},
    {"question": "She ____ be at home — her car is in the driveway.",
     "options": ["must", "should", "can", "might"], "correct": "must", "difficulty": "B2", "topic": "modals"},
    {"question": "You ____ have seen a ghost — there's no such thing!",
     "options": ["can't", "mustn't", "shouldn't", "wouldn't"], "correct": "can't", "difficulty": "B2", "topic": "modals"},
    {"question": "He ____ swim when he was only three years old.",
     "options": ["could", "was able to", "can", "might"], "correct": "could", "difficulty": "B1", "topic": "modals"},
    {"question": "You ____ have brought a gift — it really wasn't necessary.",
     "options": ["needn't", "mustn't", "couldn't", "shouldn't"], "correct": "needn't", "difficulty": "C1", "topic": "modals"},
    {"question": "We ____ leave now or we'll miss the last train.",
     "options": ["had better", "would rather", "had sooner", "would better"], "correct": "had better", "difficulty": "B2", "topic": "modals"},
    {"question": "She ____ have left already — the lights are off.",
     "options": ["must", "should", "can", "would"], "correct": "must", "difficulty": "B2", "topic": "modals"},
    {"question": "How ____ you speak to your mother like that!",
     "options": ["dare", "may", "can", "should"], "correct": "dare", "difficulty": "C1", "topic": "modals"},
    {"question": "____ I ask you a personal question?",
     "options": ["May", "Must", "Should", "Will"], "correct": "May", "difficulty": "B1", "topic": "modals"},
    {"question": "He ____ to wear a uniform when he was at school.",
     "options": ["had", "must", "should", "ought"], "correct": "had", "difficulty": "B1", "topic": "modals"},
    {"question": "Despite the heavy rain, he ____ to reach the summit.",
     "options": ["was able", "could", "can", "might"], "correct": "was able", "difficulty": "C1", "topic": "modals"},
    {"question": "You ____ smoke in here — it's strictly forbidden.",
     "options": ["mustn't", "needn't", "don't have to", "shouldn't"], "correct": "mustn't", "difficulty": "B1", "topic": "modals"},
    {"question": "She ____ be French — she speaks with a perfect Parisian accent.",
     "options": ["could", "must", "shall", "would"], "correct": "could", "difficulty": "B2", "topic": "modals"},
    {"question": "You ____ have studied harder if you wanted to pass the exam.",
     "options": ["should", "must", "could", "might"], "correct": "should", "difficulty": "B2", "topic": "modals"},
    {"question": "____ I say more, or have I made my point?",
     "options": ["Need", "Must", "Shall", "May"], "correct": "Need", "difficulty": "C2", "topic": "modals"},

    # =============================================
    # Unit 10: Communication & Media (15 Questions - Vocabulary)
    # =============================================
    {"question": "The story made the ____ of every newspaper in the country.",
     "options": ["headlines", "headings", "headers", "heads"], "correct": "headlines", "difficulty": "B2", "topic": "communication"},
    {"question": "I tried calling but couldn't get ____ to anyone at the office.",
     "options": ["through", "across", "over", "along"], "correct": "through", "difficulty": "B2", "topic": "communication"},
    {"question": "She came ____ as very confident during the interview.",
     "options": ["across", "through", "along", "about"], "correct": "across", "difficulty": "B2", "topic": "communication"},
    {"question": "You should ____ up if you want people at the back to hear you.",
     "options": ["speak", "talk", "say", "tell"], "correct": "speak", "difficulty": "B1", "topic": "communication"},
    {"question": "He was unable to ____ across his idea clearly to the board.",
     "options": ["put", "get", "take", "set"], "correct": "put", "difficulty": "C1", "topic": "communication"},
    {"question": "I heard it through the ____ that she's getting promoted.",
     "options": ["grapevine", "pipeline", "headline", "lifeline"], "correct": "grapevine", "difficulty": "C1", "topic": "communication"},
    {"question": "You need to read between the ____ to understand what he really means.",
     "options": ["lines", "words", "pages", "texts"], "correct": "lines", "difficulty": "B2", "topic": "communication"},
    {"question": "The ____ of the newspaper has been declining steadily for years.",
     "options": ["circulation", "distribution", "broadcasting", "publishing"], "correct": "circulation", "difficulty": "C1", "topic": "communication"},
    {"question": "Could you ____ in to Channel 4 tonight? There's an excellent documentary.",
     "options": ["tune", "turn", "switch", "change"], "correct": "tune", "difficulty": "B2", "topic": "communication"},
    {"question": "We need to ____ the word about the charity event.",
     "options": ["spread", "expand", "extend", "scatter"], "correct": "spread", "difficulty": "B1", "topic": "communication"},
    {"question": "I think we're on the same ____ — we both agree that changes are needed.",
     "options": ["wavelength", "frequency", "channel", "signal"], "correct": "wavelength", "difficulty": "C1", "topic": "communication"},
    {"question": "He finally got the ____ and stopped bothering her.",
     "options": ["message", "notice", "signal", "hint"], "correct": "message", "difficulty": "B2", "topic": "communication"},
    {"question": "She decided to ____ a conversation with the new colleague.",
     "options": ["hold", "do", "make", "take"], "correct": "hold", "difficulty": "B2", "topic": "communication"},
    {"question": "The ____ reported live from the conflict zone.",
     "options": ["correspondent", "reporter", "journalist", "editor"], "correct": "correspondent", "difficulty": "C1", "topic": "communication"},
    {"question": "I haven't been able to keep in ____ with many of my school friends.",
     "options": ["touch", "contact", "reach", "hand"], "correct": "touch", "difficulty": "B1", "topic": "communication"},

    # =============================================
    # Unit 11: Conditionals (15 Questions - Grammar)
    # =============================================
    {"question": "If I ____ you, I would accept the job offer immediately.",
     "options": ["were", "am", "would be", "had been"], "correct": "were", "difficulty": "B2", "topic": "conditionals"},
    {"question": "Had I known about the traffic, I ____ earlier.",
     "options": ["would have left", "will leave", "would leave", "had left"], "correct": "would have left", "difficulty": "C1", "topic": "conditionals"},
    {"question": "If she had studied medicine, she ____ a doctor now.",
     "options": ["would be", "would have been", "will be", "had been"], "correct": "would be", "difficulty": "C1", "topic": "conditionals"},
    {"question": "I'll lend you the money ____ you promise to pay me back by Friday.",
     "options": ["provided", "unless", "supposing", "otherwise"], "correct": "provided", "difficulty": "B2", "topic": "conditionals"},
    {"question": "____ it not been for your help, I would have failed the exam.",
     "options": ["Had", "If", "Were", "Should"], "correct": "Had", "difficulty": "C2", "topic": "conditionals"},
    {"question": "You can borrow my car ____ as you fill the tank before returning it.",
     "options": ["as long", "so far", "as much", "as well"], "correct": "as long", "difficulty": "B2", "topic": "conditionals"},
    {"question": "____ you need any assistance, please don't hesitate to contact us.",
     "options": ["Should", "Would", "Could", "Had"], "correct": "Should", "difficulty": "C1", "topic": "conditionals"},
    {"question": "But ____ your support, we would never have succeeded.",
     "options": ["for", "with", "from", "by"], "correct": "for", "difficulty": "C2", "topic": "conditionals"},
    {"question": "If only I ____ what I know now when I was younger!",
     "options": ["had known", "knew", "would know", "have known"], "correct": "had known", "difficulty": "B2", "topic": "conditionals"},
    {"question": "Suppose you ____ the lottery, what would you do with the money?",
     "options": ["won", "win", "would win", "had won"], "correct": "won", "difficulty": "B2", "topic": "conditionals"},
    {"question": "Were she ____ harder, she would get better results.",
     "options": ["to work", "working", "works", "worked"], "correct": "to work", "difficulty": "C1", "topic": "conditionals"},
    {"question": "I wouldn't have crashed the car if the road ____ so icy.",
     "options": ["hadn't been", "wasn't", "wouldn't be", "isn't"], "correct": "hadn't been", "difficulty": "B2", "topic": "conditionals"},
    {"question": "Take an umbrella ____ it rains later.",
     "options": ["in case", "unless", "provided", "as long as"], "correct": "in case", "difficulty": "B1", "topic": "conditionals"},
    {"question": "If you heat ice, it ____.",
     "options": ["melts", "will melt", "would melt", "melted"], "correct": "melts", "difficulty": "A2", "topic": "conditionals"},
    {"question": "He would never have been caught ____ he not confessed.",
     "options": ["had", "if", "were", "should"], "correct": "had", "difficulty": "C2", "topic": "conditionals"},

    # =============================================
    # Unit 12: Chance & Nature (15 Questions - Vocabulary)
    # =============================================
    {"question": "The disease ____ out in several villages across the region.",
     "options": ["broke", "burst", "blew", "split"], "correct": "broke", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "Several animal species have ____ out due to habitat destruction.",
     "options": ["died", "wiped", "run", "faded"], "correct": "died", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "The hurricane ____ out most of the coastal town.",
     "options": ["wiped", "swept", "cleared", "washed"], "correct": "wiped", "difficulty": "C1", "topic": "chance and nature"},
    {"question": "A few unexpected problems ____ up during the expedition.",
     "options": ["cropped", "came", "turned", "showed"], "correct": "cropped", "difficulty": "C1", "topic": "chance and nature"},
    {"question": "The drought has had a devastating effect on the local ____.",
     "options": ["ecosystem", "economy", "ecology", "environment"], "correct": "ecosystem", "difficulty": "C1", "topic": "chance and nature"},
    {"question": "We need to reduce our carbon ____ to fight climate change.",
     "options": ["footprint", "imprint", "fingerprint", "blueprint"], "correct": "footprint", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "The situation ____ out to be much worse than we had expected.",
     "options": ["turned", "came", "worked", "found"], "correct": "turned", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "She's a real force of ____ — nothing can stop her.",
     "options": ["nature", "habit", "power", "will"], "correct": "nature", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "I knew we didn't stand a ____ of winning against such a strong team.",
     "options": ["chance", "hope", "risk", "luck"], "correct": "chance", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "The eruption hit without warning — it was the calm before the ____.",
     "options": ["storm", "rain", "flood", "wind"], "correct": "storm", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "This type of bird is now an ____ species due to deforestation.",
     "options": ["endangered", "dangerous", "extinct", "exhausted"], "correct": "endangered", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "The government should invest more in ____ energy sources like solar and wind.",
     "options": ["renewable", "reusable", "recyclable", "recoverable"], "correct": "renewable", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "How did the accident come ____?",
     "options": ["about", "across", "along", "around"], "correct": "about", "difficulty": "B2", "topic": "chance and nature"},
    {"question": "The charity works to ____ the natural habitat of endangered animals.",
     "options": ["conserve", "reserve", "preserve", "observe"], "correct": "conserve", "difficulty": "C1", "topic": "chance and nature"},
    {"question": "Eclipses only happen once in a blue ____.",
     "options": ["moon", "sun", "star", "sky"], "correct": "moon", "difficulty": "B2", "topic": "chance and nature"},

    # =============================================
    # Unit 13: Unreal Time (15 Questions - Grammar)
    # =============================================
    {"question": "I wish I ____ more time to spend with my family.",
     "options": ["had", "have", "would have", "am having"], "correct": "had", "difficulty": "B2", "topic": "unreal time"},
    {"question": "If only she ____ to my advice, she wouldn't be in this mess.",
     "options": ["had listened", "listened", "would listen", "listens"], "correct": "had listened", "difficulty": "C1", "topic": "unreal time"},
    {"question": "I'd rather you ____ smoke in here, if you don't mind.",
     "options": ["didn't", "don't", "wouldn't", "won't"], "correct": "didn't", "difficulty": "C1", "topic": "unreal time"},
    {"question": "It's high time you ____ looking for a proper job.",
     "options": ["started", "start", "would start", "have started"], "correct": "started", "difficulty": "C1", "topic": "unreal time"},
    {"question": "He talks as if he ____ everything about the subject.",
     "options": ["knew", "knows", "has known", "is knowing"], "correct": "knew", "difficulty": "B2", "topic": "unreal time"},
    {"question": "I wish you ____ making that awful noise!",
     "options": ["would stop", "stopped", "stop", "had stopped"], "correct": "would stop", "difficulty": "B2", "topic": "unreal time"},
    {"question": "She looked as though she ____ crying all night.",
     "options": ["had been", "has been", "was", "is"], "correct": "had been", "difficulty": "C1", "topic": "unreal time"},
    {"question": "It's about time the government ____ something about pollution.",
     "options": ["did", "does", "will do", "has done"], "correct": "did", "difficulty": "C1", "topic": "unreal time"},
    {"question": "Suppose you ____ offered a job abroad, would you take it?",
     "options": ["were", "are", "will be", "have been"], "correct": "were", "difficulty": "B2", "topic": "unreal time"},
    {"question": "I'd sooner ____ than ask him for money.",
     "options": ["starve", "starving", "to starve", "starved"], "correct": "starve", "difficulty": "C1", "topic": "unreal time"},
    {"question": "If only I ____ taller! I'd love to play basketball.",
     "options": ["were", "am", "would be", "had been"], "correct": "were", "difficulty": "B2", "topic": "unreal time"},
    {"question": "He acts as though the company ____ to him.",
     "options": ["belonged", "belongs", "belonging", "has belonged"], "correct": "belonged", "difficulty": "C1", "topic": "unreal time"},
    {"question": "I wish I ____ that rude comment at the meeting.",
     "options": ["hadn't made", "didn't make", "wouldn't make", "haven't made"], "correct": "hadn't made", "difficulty": "B2", "topic": "unreal time"},
    {"question": "I'd rather ____ to the beach than stay at home.",
     "options": ["go", "going", "to go", "went"], "correct": "go", "difficulty": "B1", "topic": "unreal time"},
    {"question": "It's time we ____ about the future of this project.",
     "options": ["thought", "think", "will think", "are thinking"], "correct": "thought", "difficulty": "C1", "topic": "unreal time"},

    # =============================================
    # Unit 14: Quantity & Money (15 Questions - Vocabulary)
    # =============================================
    {"question": "She's been saving ____ for a deposit on a house for years.",
     "options": ["up", "out", "off", "away"], "correct": "up", "difficulty": "B1", "topic": "quantity and money"},
    {"question": "They finally managed to ____ off their mortgage last month.",
     "options": ["pay", "put", "set", "take"], "correct": "pay", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "The total bill ____ to over £500.",
     "options": ["came", "went", "got", "ran"], "correct": "came", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "We need to ____ back on our spending this month.",
     "options": ["cut", "hold", "pull", "set"], "correct": "cut", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "That restaurant is a complete rip-____. The food isn't worth the price.",
     "options": ["off", "out", "up", "away"], "correct": "off", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "She had to ____ out £3,000 for the car repairs.",
     "options": ["fork", "hand", "pay", "give"], "correct": "fork", "difficulty": "C1", "topic": "quantity and money"},
    {"question": "Many families struggle to make ends ____.",
     "options": ["meet", "match", "reach", "join"], "correct": "meet", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "The company went ____ after failing to repay its debts.",
     "options": ["bankrupt", "broken", "collapsed", "empty"], "correct": "bankrupt", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "We'll all have to tighten our ____ during the recession.",
     "options": ["belts", "ropes", "strings", "ties"], "correct": "belts", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "A good education is worth its weight in ____.",
     "options": ["gold", "silver", "money", "cash"], "correct": "gold", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "The ____ rate has risen sharply, making everything more expensive.",
     "options": ["inflation", "interest", "exchange", "tax"], "correct": "inflation", "difficulty": "C1", "topic": "quantity and money"},
    {"question": "He made a considerable ____ on the sale of his property.",
     "options": ["profit", "benefit", "gain", "win"], "correct": "profit", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "Money doesn't grow on ____.",
     "options": ["trees", "plants", "flowers", "branches"], "correct": "trees", "difficulty": "A2", "topic": "quantity and money"},
    {"question": "The new phone cost an arm and a ____.",
     "options": ["leg", "hand", "foot", "head"], "correct": "leg", "difficulty": "B2", "topic": "quantity and money"},
    {"question": "She is an excellent ____ — she always finds the best deals.",
     "options": ["economist", "economiser", "economics", "economy"], "correct": "economist", "difficulty": "C1", "topic": "quantity and money"},

    # =============================================
    # Unit 15: Adjectives & Adverbs (15 Questions - Grammar)
    # =============================================
    {"question": "The film was ____ fantastic — I loved every minute of it.",
     "options": ["absolutely", "very", "extremely", "fairly"], "correct": "absolutely", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "The ____ you practice, the better you will become.",
     "options": ["more", "most", "much", "many"], "correct": "more", "difficulty": "B1", "topic": "adjectives and adverbs"},
    {"question": "This is by ____ the best restaurant in town.",
     "options": ["far", "long", "much", "large"], "correct": "far", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "The test was nowhere ____ as difficult as I had expected.",
     "options": ["near", "close", "far", "much"], "correct": "near", "difficulty": "C1", "topic": "adjectives and adverbs"},
    {"question": "She bought a beautiful ____ Italian leather handbag.",
     "options": ["small", "leather Italian small", "Italian beautiful small", "small Italian beautiful"], "correct": "small", "difficulty": "C1", "topic": "adjectives and adverbs"},
    {"question": "The situation is ____ worse than we initially thought.",
     "options": ["considerably", "very", "absolutely", "utterly"], "correct": "considerably", "difficulty": "C1", "topic": "adjectives and adverbs"},
    {"question": "He ____ doesn't understand what the problem is.",
     "options": ["simply", "simple", "simplistic", "simplify"], "correct": "simply", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "The weather was ____ perfect for the outdoor wedding.",
     "options": ["absolutely", "very", "extremely", "highly"], "correct": "absolutely", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "This painting is ____ unique — there is nothing else like it.",
     "options": ["absolutely", "very", "extremely", "really"], "correct": "absolutely", "difficulty": "C1", "topic": "adjectives and adverbs"},
    {"question": "I can ____ believe what she told me — it's incredible!",
     "options": ["hardly", "hard", "heavy", "heavily"], "correct": "hardly", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "The new model is ____ better than the previous one.",
     "options": ["slightly", "totally", "absolutely", "utterly"], "correct": "slightly", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "______, the meeting was cancelled due to the storm.",
     "options": ["Apparently", "Apparent", "Appearing", "Appeared"], "correct": "Apparently", "difficulty": "B2", "topic": "adjectives and adverbs"},
    {"question": "The hotel was not ____ as expensive as I had feared.",
     "options": ["nearly", "closely", "hardly", "barely"], "correct": "nearly", "difficulty": "C1", "topic": "adjectives and adverbs"},
    {"question": "She was ____ disappointed with the results of the exam.",
     "options": ["bitterly", "strongly", "deeply", "vastly"], "correct": "bitterly", "difficulty": "C1", "topic": "adjectives and adverbs"},
    {"question": "He is ____ the most talented musician I have ever seen.",
     "options": ["easily", "simply", "merely", "purely"], "correct": "easily", "difficulty": "B2", "topic": "adjectives and adverbs"},
    # =============================================
    # Unit 16: Materials & Built Environment (15 Questions - Vocabulary)
    # =============================================
    {"question": "They decided to ____ up the old cottage and turn it into a B&B.",
     "options": ["do", "make", "put", "set"], "correct": "do", "difficulty": "B2", "topic": "materials"},
    {"question": "The council plans to ____ down the derelict buildings by the river.",
     "options": ["pull", "push", "knock", "tear"], "correct": "pull", "difficulty": "B2", "topic": "materials"},
    {"question": "The new sports centre was ____ from scratch in just 18 months.",
     "options": ["built", "made", "done", "set"], "correct": "built", "difficulty": "B1", "topic": "materials"},
    {"question": "House prices in the area have gone through the ____.",
     "options": ["roof", "ceiling", "floor", "wall"], "correct": "roof", "difficulty": "B2", "topic": "materials"},
    {"question": "The ____ of the building was completed before the walls went up.",
     "options": ["foundation", "basement", "ground", "base"], "correct": "foundation", "difficulty": "B2", "topic": "materials"},
    {"question": "We need to lay the ____ for future cooperation between our departments.",
     "options": ["foundations", "grounds", "bases", "floors"], "correct": "foundations", "difficulty": "C1", "topic": "materials"},
    {"question": "The neighbourhood has become rather ____ over the years.",
     "options": ["run-down", "run-out", "run-off", "run-up"], "correct": "run-down", "difficulty": "B2", "topic": "materials"},
    {"question": "They used ____ steel beams to support the structure.",
     "options": ["reinforced", "enforced", "forced", "reformed"], "correct": "reinforced", "difficulty": "C1", "topic": "materials"},
    {"question": "The ____ of the old factory created a lot of dust and noise.",
     "options": ["demolition", "demolishment", "demolishing", "demolisher"], "correct": "demolition", "difficulty": "C1", "topic": "materials"},
    {"question": "The area is suffering from urban ____: houses are being built everywhere.",
     "options": ["sprawl", "spread", "stretch", "scatter"], "correct": "sprawl", "difficulty": "C1", "topic": "materials"},
    {"question": "Everyone deserves a ____ over their head.",
     "options": ["roof", "ceiling", "cover", "shelter"], "correct": "roof", "difficulty": "B1", "topic": "materials"},
    {"question": "The building was declared ____ and all residents were evacuated.",
     "options": ["uninhabitable", "uninhabited", "uninhaled", "uninspired"], "correct": "uninhabitable", "difficulty": "C1", "topic": "materials"},
    {"question": "The hotel has been completely ____ and now looks brand new.",
     "options": ["refurbished", "refused", "returned", "refined"], "correct": "refurbished", "difficulty": "C1", "topic": "materials"},
    {"question": "They plan to ____ up a new shopping centre on the outskirts of town.",
     "options": ["put", "set", "build", "do"], "correct": "put", "difficulty": "B2", "topic": "materials"},
    {"question": "Good ____ is essential to keep a house warm in winter.",
     "options": ["insulation", "installation", "isolation", "inflation"], "correct": "insulation", "difficulty": "B2", "topic": "materials"},

    # =============================================
    # Unit 17: Clauses (15 Questions - Grammar)
    # =============================================
    {"question": "The woman ____ by the door is my sister.",
     "options": ["standing", "who standing", "stood", "stands"], "correct": "standing", "difficulty": "B2", "topic": "clauses"},
    {"question": "My neighbour, ____ dog barks all night, has finally moved out.",
     "options": ["whose", "who's", "which", "that"], "correct": "whose", "difficulty": "B2", "topic": "clauses"},
    {"question": "The letter ____ by hand was from my grandmother.",
     "options": ["written", "writing", "wrote", "which writing"], "correct": "written", "difficulty": "B2", "topic": "clauses"},
    {"question": "____ surprised me was his complete lack of remorse.",
     "options": ["What", "That", "Which", "It"], "correct": "What", "difficulty": "C1", "topic": "clauses"},
    {"question": "____ finished the work, she decided to go home.",
     "options": ["Having", "Have", "Had", "Being"], "correct": "Having", "difficulty": "C1", "topic": "clauses"},
    {"question": "It is essential that everyone ____ the meeting.",
     "options": ["attend", "attends", "attending", "attended"], "correct": "attend", "difficulty": "C1", "topic": "clauses"},
    {"question": "The city, ____ I visited last summer, was absolutely stunning.",
     "options": ["which", "that", "where", "what"], "correct": "which", "difficulty": "B2", "topic": "clauses"},
    {"question": "Weather ____, we'll have the party outdoors.",
     "options": ["permitting", "permitted", "permits", "to permit"], "correct": "permitting", "difficulty": "C1", "topic": "clauses"},
    {"question": "Not ____ what to do, she called her mother for advice.",
     "options": ["knowing", "known", "knew", "to know"], "correct": "knowing", "difficulty": "C1", "topic": "clauses"},
    {"question": "The reason ____ I left was that I felt undervalued.",
     "options": ["why", "which", "that", "for"], "correct": "why", "difficulty": "B2", "topic": "clauses"},
    {"question": "No sooner had I sat down ____ the phone rang.",
     "options": ["than", "when", "that", "as"], "correct": "than", "difficulty": "C1", "topic": "clauses"},
    {"question": "____ that he was innocent, the jury acquitted him.",
     "options": ["Given", "Giving", "Gave", "Give"], "correct": "Given", "difficulty": "C1", "topic": "clauses"},
    {"question": "The book, the title ____ I've forgotten, was excellent.",
     "options": ["of which", "which", "that", "whose"], "correct": "of which", "difficulty": "C2", "topic": "clauses"},
    {"question": "He spoke ____ he were in charge, but he was just an intern.",
     "options": ["as though", "even though", "as long as", "in order that"], "correct": "as though", "difficulty": "C1", "topic": "clauses"},
    {"question": "____ from above, the landscape looked like a patchwork quilt.",
     "options": ["Seen", "Seeing", "Having seen", "To see"], "correct": "Seen", "difficulty": "C1", "topic": "clauses"},

    # =============================================
    # Unit 18: Reactions & Health (15 Questions - Vocabulary)
    # =============================================
    {"question": "I think I'm coming ____ with a cold.",
     "options": ["down", "up", "over", "through"], "correct": "down", "difficulty": "B1", "topic": "health"},
    {"question": "It took her weeks to get ____ the flu.",
     "options": ["over", "through", "past", "by"], "correct": "over", "difficulty": "B1", "topic": "health"},
    {"question": "He ____ out during the ceremony because of the extreme heat.",
     "options": ["passed", "fell", "dropped", "blacked"], "correct": "passed", "difficulty": "B2", "topic": "health"},
    {"question": "The doctor gave me a ____ for some strong antibiotics.",
     "options": ["prescription", "description", "subscription", "inscription"], "correct": "prescription", "difficulty": "B2", "topic": "health"},
    {"question": "She's feeling a bit under the ____ today.",
     "options": ["weather", "cloud", "rain", "storm"], "correct": "weather", "difficulty": "B2", "topic": "health"},
    {"question": "Don't worry, he's on the ____. He should be back at work next week.",
     "options": ["mend", "fix", "heal", "cure"], "correct": "mend", "difficulty": "B2", "topic": "health"},
    {"question": "The patient is running a high ____.",
     "options": ["temperature", "degree", "heat", "warmth"], "correct": "temperature", "difficulty": "B1", "topic": "health"},
    {"question": "The disease is highly ____ and spreads through droplets.",
     "options": ["contagious", "conscious", "continuous", "contiguous"], "correct": "contagious", "difficulty": "C1", "topic": "health"},
    {"question": "She was given a clean bill of ____ by the specialist.",
     "options": ["health", "fitness", "wellness", "safety"], "correct": "health", "difficulty": "B2", "topic": "health"},
    {"question": "The medicine may cause some unpleasant side ____.",
     "options": ["effects", "results", "impacts", "consequences"], "correct": "effects", "difficulty": "B2", "topic": "health"},
    {"question": "My grandmother is as fit as a ____ for her age.",
     "options": ["fiddle", "violin", "drum", "flute"], "correct": "fiddle", "difficulty": "B2", "topic": "health"},
    {"question": "He's been fighting ____ a nasty virus all week.",
     "options": ["off", "away", "back", "out"], "correct": "off", "difficulty": "B2", "topic": "health"},
    {"question": "The ____ showed that she had a mild infection.",
     "options": ["diagnosis", "prognosis", "analysis", "synopsis"], "correct": "diagnosis", "difficulty": "C1", "topic": "health"},
    {"question": "She broke ____ in a terrible rash after eating shellfish.",
     "options": ["out", "up", "down", "off"], "correct": "out", "difficulty": "B2", "topic": "health"},
    {"question": "He had to go under the ____ for a knee replacement.",
     "options": ["knife", "blade", "scalpel", "scissors"], "correct": "knife", "difficulty": "C1", "topic": "health"},

    # =============================================
    # Unit 19: Complex Sentences (15 Questions - Grammar)
    # =============================================
    {"question": "Never ____ I experienced such terrible service.",
     "options": ["have", "had", "did", "was"], "correct": "have", "difficulty": "C1", "topic": "complex sentences"},
    {"question": "Not only ____ she win the race, but she also broke the record.",
     "options": ["did", "has", "was", "had"], "correct": "did", "difficulty": "C1", "topic": "complex sentences"},
    {"question": "It ____ John who suggested the idea in the first place.",
     "options": ["was", "is", "were", "has been"], "correct": "was", "difficulty": "B2", "topic": "complex sentences"},
    {"question": "What I really ____ is a long holiday by the sea.",
     "options": ["need", "needs", "needed", "needing"], "correct": "need", "difficulty": "B2", "topic": "complex sentences"},
    {"question": "Rarely ____ such a talented young musician.",
     "options": ["do we see", "we see", "we do see", "see we"], "correct": "do we see", "difficulty": "C1", "topic": "complex sentences"},
    {"question": "Little ____ they realise how much trouble they were in.",
     "options": ["did", "do", "had", "would"], "correct": "did", "difficulty": "C2", "topic": "complex sentences"},
    {"question": "Brilliant ____ she is, she still makes careless mistakes.",
     "options": ["though", "although", "despite", "however"], "correct": "though", "difficulty": "C1", "topic": "complex sentences"},
    {"question": "All ____ want is some peace and quiet.",
     "options": ["I", "that I", "what I", "which I"], "correct": "I", "difficulty": "B2", "topic": "complex sentences"},
    {"question": "Under no circumstances ____ you leave this building.",
     "options": ["should", "you should", "shall you", "do you"], "correct": "should", "difficulty": "C1", "topic": "complex sentences"},
    {"question": "I find ____ difficult to believe that he would lie.",
     "options": ["it", "that", "this", "which"], "correct": "it", "difficulty": "B2", "topic": "complex sentences"},
    {"question": "'Are you coming tonight?' — 'I ____ .'",
     "options": ["might", "might do", "might to", "might be"], "correct": "might", "difficulty": "B2", "topic": "complex sentences"},
    {"question": "She can play the violin and so ____ her brother.",
     "options": ["can", "does", "is", "has"], "correct": "can", "difficulty": "B1", "topic": "complex sentences"},
    {"question": "On no account ____ this information be shared with outsiders.",
     "options": ["must", "you must", "it must", "must you"], "correct": "must", "difficulty": "C1", "topic": "complex sentences"},
    {"question": "The reason ____ I didn't come was that I was ill.",
     "options": ["why", "which", "that", "for"], "correct": "why", "difficulty": "B2", "topic": "complex sentences"},
    {"question": "As far as I'm ____, the matter is closed.",
     "options": ["concerned", "concerning", "concern", "concerns"], "correct": "concerned", "difficulty": "C1", "topic": "complex sentences"},

    # =============================================
    # Unit 20: Power & Social Issues (15 Questions - Vocabulary)
    # =============================================
    {"question": "The government needs to ____ the problem of homelessness.",
     "options": ["tackle", "handle", "manage", "treat"], "correct": "tackle", "difficulty": "C1", "topic": "social issues"},
    {"question": "They launched a campaign to raise ____ about mental health.",
     "options": ["awareness", "knowledge", "attention", "conscience"], "correct": "awareness", "difficulty": "B2", "topic": "social issues"},
    {"question": "The new law will come ____ force next January.",
     "options": ["into", "to", "in", "under"], "correct": "into", "difficulty": "C1", "topic": "social issues"},
    {"question": "The police are trying to clamp ____ on illegal parking.",
     "options": ["down", "up", "off", "out"], "correct": "down", "difficulty": "C1", "topic": "social issues"},
    {"question": "You shouldn't turn a blind ____ to injustice.",
     "options": ["eye", "ear", "face", "head"], "correct": "eye", "difficulty": "B2", "topic": "social issues"},
    {"question": "Everyone should stand ____ for their rights.",
     "options": ["up", "out", "by", "off"], "correct": "up", "difficulty": "B1", "topic": "social issues"},
    {"question": "The ____ between rich and poor continues to widen.",
     "options": ["gap", "hole", "space", "distance"], "correct": "gap", "difficulty": "B2", "topic": "social issues"},
    {"question": "These reforms were brought ____ by the previous government.",
     "options": ["about", "up", "out", "forward"], "correct": "about", "difficulty": "C1", "topic": "social issues"},
    {"question": "The ____ that be have decided to cut funding for the arts.",
     "options": ["powers", "forces", "authorities", "rulers"], "correct": "powers", "difficulty": "C1", "topic": "social issues"},
    {"question": "He was accused of ____ and abuse of his position.",
     "options": ["corruption", "disruption", "eruption", "interruption"], "correct": "corruption", "difficulty": "C1", "topic": "social issues"},
    {"question": "The campaign aims to stamp ____ racism in schools.",
     "options": ["out", "off", "down", "up"], "correct": "out", "difficulty": "C1", "topic": "social issues"},
    {"question": "Every citizen has the right to vote in a free and fair ____.",
     "options": ["ballot", "poll", "survey", "census"], "correct": "ballot", "difficulty": "C1", "topic": "social issues"},
    {"question": "She refused to toe the ____ and was dismissed from the party.",
     "options": ["line", "mark", "rule", "edge"], "correct": "line", "difficulty": "C1", "topic": "social issues"},
    {"question": "The charity works to ____ funds for children in poverty.",
     "options": ["raise", "rise", "lift", "grow"], "correct": "raise", "difficulty": "B1", "topic": "social issues"},
    {"question": "Discrimination on the basis of gender is against the ____.",
     "options": ["law", "rule", "right", "order"], "correct": "law", "difficulty": "B1", "topic": "social issues"},

    # =============================================
    # Unit 21: Noun Phrases (15 Questions - Grammar)
    # =============================================
    {"question": "The ____ should be given more support by the government.",
     "options": ["elderly", "elder", "elders", "older"], "correct": "elderly", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "____ is precious and should never be taken for granted.",
     "options": ["Freedom", "The freedom", "A freedom", "Freedoms"], "correct": "Freedom", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "A great ____ of research has been done on the topic.",
     "options": ["deal", "number", "amount", "quantity"], "correct": "deal", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "There are ____ people who believe in ghosts.",
     "options": ["few", "a few", "little", "a little"], "correct": "few", "difficulty": "B2", "topic": "noun phrases"},
    {"question": "She is ____ doctor — one of the best in the country.",
     "options": ["a", "the", "an", "—"], "correct": "a", "difficulty": "B1", "topic": "noun phrases"},
    {"question": "A friend of ____ told me the news.",
     "options": ["John's", "John", "Johns", "the John"], "correct": "John's", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "____ majority of students passed the exam.",
     "options": ["The", "A", "—", "An"], "correct": "The", "difficulty": "B2", "topic": "noun phrases"},
    {"question": "The ____ of the system led to significant losses.",
     "options": ["failure", "failing", "fail", "failed"], "correct": "failure", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "There was ____ information available on the subject.",
     "options": ["little", "few", "a few", "less"], "correct": "little", "difficulty": "B2", "topic": "noun phrases"},
    {"question": "____ child deserves access to quality education.",
     "options": ["Every", "All", "Whole", "Both"], "correct": "Every", "difficulty": "B1", "topic": "noun phrases"},
    {"question": "The ____ for intervention was widely recognised.",
     "options": ["need", "needing", "needed", "needs"], "correct": "need", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "She had ____ money left after paying the rent.",
     "options": ["a little", "a few", "few", "many"], "correct": "a little", "difficulty": "B2", "topic": "noun phrases"},
    {"question": "____ of the candidates met the requirements.",
     "options": ["Neither", "None", "Either", "Both"], "correct": "Neither", "difficulty": "B2", "topic": "noun phrases"},
    {"question": "His ____ to the team was invaluable.",
     "options": ["contribution", "contributing", "contributed", "contributor"], "correct": "contribution", "difficulty": "C1", "topic": "noun phrases"},
    {"question": "The company's ____ have risen sharply this year.",
     "options": ["profits", "profit's", "profiting", "profitable"], "correct": "profits", "difficulty": "B2", "topic": "noun phrases"},

    # =============================================
    # Unit 22: Quality & The Arts (15 Questions - Vocabulary)
    # =============================================
    {"question": "She ____ up painting when she retired from her job.",
     "options": ["took", "gave", "picked", "set"], "correct": "took", "difficulty": "B1", "topic": "arts"},
    {"question": "The film didn't live ____ to my expectations at all.",
     "options": ["up", "on", "out", "through"], "correct": "up", "difficulty": "B2", "topic": "arts"},
    {"question": "She completely stole the ____ at the awards ceremony.",
     "options": ["show", "stage", "act", "scene"], "correct": "show", "difficulty": "B2", "topic": "arts"},
    {"question": "The band's new album received ____ reviews from the critics.",
     "options": ["rave", "raving", "raved", "raves"], "correct": "rave", "difficulty": "C1", "topic": "arts"},
    {"question": "He's always been in the ____ ever since his first film.",
     "options": ["limelight", "spotlight", "flashlight", "daylight"], "correct": "limelight", "difficulty": "C1", "topic": "arts"},
    {"question": "A lot of work goes on behind the ____ to make a play successful.",
     "options": ["scenes", "stage", "curtain", "screen"], "correct": "scenes", "difficulty": "B2", "topic": "arts"},
    {"question": "The audience gave them a standing ____.",
     "options": ["ovation", "applause", "cheer", "clap"], "correct": "ovation", "difficulty": "C1", "topic": "arts"},
    {"question": "The gallery is holding an ____ of modern sculpture.",
     "options": ["exhibition", "exhibit", "exhibitor", "exhibiting"], "correct": "exhibition", "difficulty": "B2", "topic": "arts"},
    {"question": "He's a tough ____ to follow — his presentation was brilliant.",
     "options": ["act", "show", "play", "scene"], "correct": "act", "difficulty": "C1", "topic": "arts"},
    {"question": "Let's just play it by ____ and see what happens.",
     "options": ["ear", "eye", "hand", "heart"], "correct": "ear", "difficulty": "B2", "topic": "arts"},
    {"question": "The artist's latest ____ will be displayed at the national gallery.",
     "options": ["masterpiece", "masterwork", "master", "mastery"], "correct": "masterpiece", "difficulty": "B2", "topic": "arts"},
    {"question": "She has a real artistic ____ when it comes to interior design.",
     "options": ["flair", "flare", "fair", "fare"], "correct": "flair", "difficulty": "C1", "topic": "arts"},
    {"question": "The publisher is about to ____ out her third novel.",
     "options": ["bring", "put", "take", "set"], "correct": "bring", "difficulty": "B2", "topic": "arts"},
    {"question": "She really looks ____ to her music teacher.",
     "options": ["up", "on", "at", "after"], "correct": "up", "difficulty": "B1", "topic": "arts"},
    {"question": "The ____ of the new theatre was attended by several celebrities.",
     "options": ["premiere", "premier", "primary", "prime"], "correct": "premiere", "difficulty": "C1", "topic": "arts"},

    # =============================================
    # Unit 23: Verbal Complements (15 Questions - Grammar)
    # =============================================
    {"question": "I remember ____ him at a conference years ago.",
     "options": ["meeting", "to meet", "meet", "met"], "correct": "meeting", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "Don't forget ____ the door when you leave.",
     "options": ["to lock", "locking", "lock", "locked"], "correct": "to lock", "difficulty": "B1", "topic": "verbal complements"},
    {"question": "He stopped ____ a cigarette on his way to work.",
     "options": ["to have", "having", "have", "had"], "correct": "to have", "difficulty": "C1", "topic": "verbal complements"},
    {"question": "She denied ____ anything about the missing money.",
     "options": ["knowing", "to know", "know", "knew"], "correct": "knowing", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "I tried ____ the window, but it was stuck.",
     "options": ["opening", "to open", "open", "opened"], "correct": "opening", "difficulty": "C1", "topic": "verbal complements"},
    {"question": "He went on ____ a very successful businessman.",
     "options": ["to become", "becoming", "become", "became"], "correct": "to become", "difficulty": "C1", "topic": "verbal complements"},
    {"question": "There's no point ____ arguing about it now.",
     "options": ["in", "of", "to", "for"], "correct": "in", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "I can't help ____ every time I see that video.",
     "options": ["laughing", "to laugh", "laugh", "laughed"], "correct": "laughing", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "She made him ____ for his rude behaviour.",
     "options": ["apologise", "to apologise", "apologising", "apologised"], "correct": "apologise", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "I look forward ____ hearing from you soon.",
     "options": ["to", "for", "at", "on"], "correct": "to", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "Let me ____ you with those heavy bags.",
     "options": ["help", "to help", "helping", "helped"], "correct": "help", "difficulty": "B1", "topic": "verbal complements"},
    {"question": "She suggested ____ to a different restaurant.",
     "options": ["going", "to go", "go", "went"], "correct": "going", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "It's no use ____ over spilt milk.",
     "options": ["crying", "to cry", "cry", "cried"], "correct": "crying", "difficulty": "B2", "topic": "verbal complements"},
    {"question": "I want you ____ me the truth.",
     "options": ["to tell", "telling", "tell", "told"], "correct": "to tell", "difficulty": "B1", "topic": "verbal complements"},
    {"question": "She managed ____ the exam despite being ill.",
     "options": ["to pass", "passing", "pass", "passed"], "correct": "to pass", "difficulty": "B2", "topic": "verbal complements"},

    # =============================================
    # Unit 24: Relationships & People (15 Questions - Vocabulary)
    # =============================================
    {"question": "She doesn't get ____ with her new colleagues very well.",
     "options": ["on", "up", "by", "in"], "correct": "on", "difficulty": "B1", "topic": "relationships"},
    {"question": "They fell ____ over a trivial matter and haven't spoken since.",
     "options": ["out", "off", "down", "through"], "correct": "out", "difficulty": "B2", "topic": "relationships"},
    {"question": "After their argument, it took them weeks to make ____.",
     "options": ["up", "out", "off", "over"], "correct": "up", "difficulty": "B1", "topic": "relationships"},
    {"question": "I think we got off on the wrong ____ when we first met.",
     "options": ["foot", "hand", "start", "side"], "correct": "foot", "difficulty": "B2", "topic": "relationships"},
    {"question": "We don't see eye to ____ on many things.",
     "options": ["eye", "face", "head", "mind"], "correct": "eye", "difficulty": "B2", "topic": "relationships"},
    {"question": "She gave me the cold ____ at the party.",
     "options": ["shoulder", "hand", "back", "face"], "correct": "shoulder", "difficulty": "B2", "topic": "relationships"},
    {"question": "He has a heart of ____ — always helping others.",
     "options": ["gold", "silver", "stone", "iron"], "correct": "gold", "difficulty": "B1", "topic": "relationships"},
    {"question": "Over the years, they gradually grew ____.",
     "options": ["apart", "away", "off", "out"], "correct": "apart", "difficulty": "B2", "topic": "relationships"},
    {"question": "She was ____ up by her grandparents after her parents died.",
     "options": ["brought", "grown", "raised", "taken"], "correct": "brought", "difficulty": "B2", "topic": "relationships"},
    {"question": "He's completely ____ — he pretends to be nice but talks behind your back.",
     "options": ["two-faced", "double-minded", "two-sided", "split-faced"], "correct": "two-faced", "difficulty": "C1", "topic": "relationships"},
    {"question": "She still holds a ____ against him for what he did years ago.",
     "options": ["grudge", "anger", "hate", "blame"], "correct": "grudge", "difficulty": "C1", "topic": "relationships"},
    {"question": "True friendship requires mutual ____ and understanding.",
     "options": ["respect", "inspect", "suspect", "aspect"], "correct": "respect", "difficulty": "B1", "topic": "relationships"},
    {"question": "He tried to make ____ for his past behaviour by being extra kind.",
     "options": ["amends", "repairs", "fixes", "changes"], "correct": "amends", "difficulty": "C1", "topic": "relationships"},
    {"question": "I can always ____ on my best friend in times of need.",
     "options": ["rely", "depend", "count", "trust"], "correct": "rely", "difficulty": "B2", "topic": "relationships"},
    {"question": "Their ____ has lasted over thirty wonderful years.",
     "options": ["friendship", "friendly", "friendliness", "befriending"], "correct": "friendship", "difficulty": "B1", "topic": "relationships"},

    # =============================================
    # Unit 25: Reporting (15 Questions - Grammar)
    # =============================================
    {"question": "She said she ____ tired and wanted to go home.",
     "options": ["was", "is", "has been", "will be"], "correct": "was", "difficulty": "B1", "topic": "reporting"},
    {"question": "He denied ____ the money from the safe.",
     "options": ["having taken", "to take", "take", "took"], "correct": "having taken", "difficulty": "C1", "topic": "reporting"},
    {"question": "She asked me ____ I was enjoying the party.",
     "options": ["whether", "that", "what", "which"], "correct": "whether", "difficulty": "B2", "topic": "reporting"},
    {"question": "He ____ me not to tell anyone about the surprise.",
     "options": ["told", "said", "spoke", "talked"], "correct": "told", "difficulty": "B1", "topic": "reporting"},
    {"question": "The doctor advised him ____ smoking immediately.",
     "options": ["to stop", "stopping", "stop", "stopped"], "correct": "to stop", "difficulty": "B2", "topic": "reporting"},
    {"question": "She ____ that we should leave early to avoid traffic.",
     "options": ["suggested", "told", "said me", "informed"], "correct": "suggested", "difficulty": "B2", "topic": "reporting"},
    {"question": "He ____ to help us move house next weekend.",
     "options": ["offered", "suggested", "denied", "recommended"], "correct": "offered", "difficulty": "B2", "topic": "reporting"},
    {"question": "The teacher reminded the students ____ their homework.",
     "options": ["to submit", "submitting", "submit", "submitted"], "correct": "to submit", "difficulty": "B2", "topic": "reporting"},
    {"question": "He ____ having been at the scene of the crime.",
     "options": ["denied", "refused", "rejected", "declined"], "correct": "denied", "difficulty": "C1", "topic": "reporting"},
    {"question": "She ____ on paying for the meal, despite our protests.",
     "options": ["insisted", "persisted", "resisted", "consisted"], "correct": "insisted", "difficulty": "C1", "topic": "reporting"},
    {"question": "He asked me what time the meeting ____.",
     "options": ["started", "starts", "starting", "has started"], "correct": "started", "difficulty": "B2", "topic": "reporting"},
    {"question": "They demanded that he ____ immediately.",
     "options": ["resign", "resigns", "resigned", "resigning"], "correct": "resign", "difficulty": "C2", "topic": "reporting"},
    {"question": "She threatened ____ the police if he didn't leave.",
     "options": ["to call", "calling", "call", "called"], "correct": "to call", "difficulty": "B2", "topic": "reporting"},
    {"question": "He ____ that he had made a terrible mistake.",
     "options": ["admitted", "denied", "refused", "offered"], "correct": "admitted", "difficulty": "B2", "topic": "reporting"},
    {"question": "He ____ about having won the competition three times.",
     "options": ["boasted", "announced", "declared", "stated"], "correct": "boasted", "difficulty": "C1", "topic": "reporting"},

    # =============================================
    # Unit 26: Preference & Leisure (15 Questions - Vocabulary)
    # =============================================
    {"question": "He's a real couch ____ — he never does any exercise.",
     "options": ["potato", "tomato", "bean", "pea"], "correct": "potato", "difficulty": "B2", "topic": "leisure"},
    {"question": "She decided to take ____ yoga to help her relax.",
     "options": ["up", "on", "in", "over"], "correct": "up", "difficulty": "B1", "topic": "leisure"},
    {"question": "After a long week, I just need to ____ down.",
     "options": ["wind", "slow", "calm", "cool"], "correct": "wind", "difficulty": "B2", "topic": "leisure"},
    {"question": "Let your hair ____ and enjoy the party!",
     "options": ["down", "out", "up", "off"], "correct": "down", "difficulty": "B2", "topic": "leisure"},
    {"question": "She had the time of her ____ on holiday in Greece.",
     "options": ["life", "day", "world", "age"], "correct": "life", "difficulty": "B1", "topic": "leisure"},
    {"question": "I need to recharge my ____ after such a busy month.",
     "options": ["batteries", "energy", "power", "strength"], "correct": "batteries", "difficulty": "B2", "topic": "leisure"},
    {"question": "She's very ____ on photography and takes her camera everywhere.",
     "options": ["keen", "fond", "eager", "willing"], "correct": "keen", "difficulty": "B1", "topic": "leisure"},
    {"question": "Would you like to join ____ our game of football?",
     "options": ["in", "on", "up", "to"], "correct": "in", "difficulty": "B1", "topic": "leisure"},
    {"question": "He spends most of his ____ time reading books.",
     "options": ["spare", "free", "empty", "blank"], "correct": "spare", "difficulty": "B1", "topic": "leisure"},
    {"question": "I'm not really ____ for going out tonight — I'm exhausted.",
     "options": ["up", "on", "in", "at"], "correct": "up", "difficulty": "B2", "topic": "leisure"},
    {"question": "She gave ____ tennis after injuring her shoulder.",
     "options": ["up", "in", "out", "away"], "correct": "up", "difficulty": "B1", "topic": "leisure"},
    {"question": "I usually work ____ at the gym three times a week.",
     "options": ["out", "up", "off", "in"], "correct": "out", "difficulty": "B1", "topic": "leisure"},
    {"question": "They like to hang ____ at the shopping centre after school.",
     "options": ["out", "on", "up", "around"], "correct": "out", "difficulty": "B1", "topic": "leisure"},
    {"question": "He is a keen ____ of extreme sports like skydiving.",
     "options": ["enthusiast", "fanatic", "admirer", "spectator"], "correct": "enthusiast", "difficulty": "C1", "topic": "leisure"},
    {"question": "The ____ atmosphere of the spa helped her relax completely.",
     "options": ["recreational", "creative", "competitive", "aggressive"], "correct": "recreational", "difficulty": "C1", "topic": "leisure"},
]

def seed_questions():
    db = SessionLocal()

    # Clear old questions for topics we are about to seed
    topics = set(q["topic"] for q in questions)
    for t in topics:
        db.query(QuestionBank).filter(QuestionBank.topic == t).delete()
    
    db.commit()

    for q in questions:
        question = QuestionBank(**q)
        db.add(question)

    db.commit()
    db.close()

    print(f"{len(questions)} questions inserted successfully")

if __name__ == "__main__":
    seed_questions()